newnstein/newnstein/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls import (
handler400, handler403, handler404, handler500
)

handler400 = 'home.views.error400'
handler403 = 'home.views.error403'
handler404 = 'home.views.error404'
handler500 = 'home.views.error500'

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'home.views.home', name='home'),
    url(r'^(?P<class_id>\d+)/', include('dashboard.urls')),
    url(r'^dashboard/$', 'dashboard.views.dashboard', name="dashboard"),
    url(r'^accounts/', include('account.urls')),
    url(r'^settings/', include('settings.urls')),
]

newnstein/quiz/urls.py
from django.conf.urls import patterns, url

from .views import CategoriesListView,\
    ViewQuizListByCategory, QuizUserProgressView, QuizMarkingList,\
    QuizMarkingDetail, QuizDetailView, QuizTake


urlpatterns = patterns('',
                        url(r'^$', 'quiz.views.view_all_quizzes', name='view_all_quizzes'),
                        url(r'^add/$', 'quiz.views.create_quiz', name='create_quiz'),
                        url(r'^(?P<quiz_id>\d+)/edit/(?P<question_id>\d+)/$', 'quiz.views.edit_quiz', name='edit_quiz'),
                        url(r'^(?P<quiz_id>\d+)/edit/(?P<question_id>\d+)/true/$', 'quiz.views.update_tf_question', name='update_tf_question'),
                        url(r'^(?P<quiz_id>\d+)/edit/(?P<question_id>\d+)/multiple/$', 'quiz.views.update_mc_question', name='update_mc_question'),
                        url(r'^(?P<quiz_id>\d+)/edit/(?P<question_id>\d+)/essay/$', 'quiz.views.update_essay_question', name='update_essay_question'),
                        url(r'^(?P<quiz_id>\d+)/view/$', 'quiz.views.view_quiz', name='view_quiz'),
                        url(r'^(?P<quiz_id>\d+)/delete/$', 'quiz.views.delete_quiz', name='delete_quiz'),
                        url(r'^(?P<quiz_id>\d+)/add_question/$', 'quiz.views.add_question', name='add_question'),
                        url(r'^(?P<quiz_id>\d+)/add_question/true/$', 'quiz.views.add_tf_question', name='add_tf_question'),
                        url(r'^(?P<quiz_id>\d+)/add_question/multiple/$', 'quiz.views.add_mc_question', name='add_mc_question'),
                        url(r'^(?P<quiz_id>\d+)/add_question/essay/$', 'quiz.views.add_essay_question', name='add_essay_question'),

                        url(regex=r'^category/$', view=CategoriesListView.as_view(), name='quiz_category_list_all'),
                        url(regex=r'^category/(?P<category_name>[\w|\W-]+)/$', view=ViewQuizListByCategory.as_view(), name='quiz_category_list_matching'),
                        url(regex=r'^progress/$', view=QuizUserProgressView.as_view(), name='quiz_progress'),
                        url(regex=r'^marking/$', view=QuizMarkingList.as_view(), name='quiz_marking'),
                        url(regex=r'^marking/(?P<pk>[\d.]+)/$', view=QuizMarkingDetail.as_view(), name='quiz_marking_detail'),
                        url(regex=r'^(?P<slug>\d+)/$', view=QuizDetailView.as_view(), name='quiz_start_page'),
                        url(regex=r'^(?P<quiz_name>[\w-]+)/take/$', view=QuizTake.as_view(), name='quiz_question'),
)

newnstein/quiz/models.py
from __future__ import unicode_literals
import re
import json
import datetime

from django.db import models
from django.core.exceptions import ValidationError, ImproperlyConfigured
from django.core.validators import MaxValueValidator
from django.utils.translation import ugettext as _
from django.utils.timezone import now
from django.utils.encoding import python_2_unicode_compatible
from django.conf import settings

from model_utils.managers import InheritanceManager


class CategoryManager(models.Manager):

    def new_category(self, category):
        new_category = self.create(category=re.sub('\s+', '-', category)
                                   .lower())

        new_category.save()
        return new_category


@python_2_unicode_compatible
class Category(models.Model):

    category = models.CharField(
        verbose_name=_("Category"),
        max_length=250, blank=True,
        unique=True, null=True)

    objects = CategoryManager()

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.category


@python_2_unicode_compatible
class SubCategory(models.Model):

    sub_category = models.CharField(
        verbose_name=_("Sub-Category"),
        max_length=250, blank=True, null=True)

    category = models.ForeignKey(
        Category, null=True, blank=True,
        verbose_name=_("Category"))

    objects = CategoryManager()

    class Meta:
        verbose_name = _("Sub-Category")
        verbose_name_plural = _("Sub-Categories")

    def __str__(self):
        return self.sub_category + " (" + self.category.category + ")"


@python_2_unicode_compatible
class Quiz(models.Model):

    title = models.CharField(
        verbose_name=_("Title"),
        max_length=60, blank=False)

    description = models.TextField(
        verbose_name=_("Description"),
        blank=True, help_text=_("a description of the quiz"))

    category = models.CharField(
        max_length=60,
        blank=True, verbose_name=_("Category"))

    random_order = models.BooleanField(
        blank=False, default=False,
        verbose_name=_("Random Order"),
        help_text=_("Display the questions in "
                    "a random order or as they "
                    "are set?"))

    max_questions = models.PositiveIntegerField(
        blank=True, null=True, verbose_name=_("Max Questions"),
        help_text=_("Number of questions to be answered on each attempt."))

    answers_at_end = models.BooleanField(
        blank=False, default=False,
        help_text=_("Correct answer is NOT shown after question."
                    " Answers displayed at the end."),
        verbose_name=_("Answers at end"))

    exam_paper = models.BooleanField(
        blank=False, default=False,
        help_text=_("If yes, the result of each"
                    " attempt by a user will be"
                    " stored. Necessary for marking."),
        verbose_name=_("Exam Paper"))

    single_attempt = models.BooleanField(
        blank=False, default=False,
        help_text=_("If yes, only one attempt by"
                    " a user will be permitted."
                    " Non users cannot sit this exam."),
        verbose_name=_("Single Attempt"))

    pass_mark = models.SmallIntegerField(
        blank=True, default=0,
        verbose_name=_("Pass Mark"),
        help_text=_("Percentage required to pass exam."),
        validators=[MaxValueValidator(100)])

    success_text = models.TextField(
        blank=True, help_text=_("Displayed if user passes."),
        verbose_name=_("Success Text"))

    fail_text = models.TextField(
        verbose_name=_("Fail Text"),
        blank=True, help_text=_("Displayed if user fails."))

    draft = models.BooleanField(
        blank=True, default=False,
        verbose_name=_("Draft"),
        help_text=_("If yes, the quiz is not displayed"
                    " in the quiz list and can only be"
                    " taken by users who can edit"
                    " quizzes."))

    date_added = models.DateTimeField(
        default=datetime.datetime.now,
        verbose_name=_("Date"),
        blank=True)

    class_id = models.IntegerField(default=1)


    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        if self.single_attempt is True:
            self.exam_paper = True

        if self.pass_mark > 100:
            raise ValidationError('%s is above 100' % self.pass_mark)

        super(Quiz, self).save(force_insert, force_update, *args, **kwargs)

    class Meta:
        verbose_name = _("Quiz")
        verbose_name_plural = _("Quizzes")

    def __str__(self):
        return self.title

    def get_questions(self):
        return self.question_set.all().select_subclasses()

    @property
    def get_max_score(self):
        return self.get_questions().count()

    def anon_score_id(self):
        return str(self.id) + "_score"

    def anon_q_list(self):
        return str(self.id) + "_q_list"

    def anon_q_data(self):
        return str(self.id) + "_data"


class ProgressManager(models.Manager):

    def new_progress(self, user):
        new_progress = self.create(user=user,
                                   score="")
        new_progress.save()
        return new_progress


class Progress(models.Model):
    """
    Progress is used to track an individual signed in users score on different
    quiz's and categories

    Data stored in csv using the format:
        category, score, possible, category, score, possible, ...
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL, verbose_name=_("User"))

    score = models.CommaSeparatedIntegerField(max_length=1024,
                                              verbose_name=_("Score"))

    objects = ProgressManager()

    class Meta:
        verbose_name = _("User Progress")
        verbose_name_plural = _("User progress records")

    @property
    def list_all_cat_scores(self):
        """
        Returns a dict in which the key is the category name and the item is
        a list of three integers.

        The first is the number of questions correct,
        the second is the possible best score,
        the third is the percentage correct.

        The dict will have one key for every category that you have defined
        """
        score_before = self.score
        output = {}

        for cat in Category.objects.all():
            to_find = re.escape(cat.category) + r",(\d+),(\d+),"
            #  group 1 is score, group 2 is highest possible

            match = re.search(to_find, self.score, re.IGNORECASE)

            if match:
                score = int(match.group(1))
                possible = int(match.group(2))

                try:
                    percent = int(round((float(score) / float(possible))
                                        * 100))
                except:
                    percent = 0

                output[cat.category] = [score, possible, percent]

            else:  # if category has not been added yet, add it.
                self.score += cat.category + ",0,0,"
                output[cat.category] = [0, 0]

        if len(self.score) > len(score_before):
            # If a new category has been added, save changes.
            self.save()

        return output

    def update_score(self, question, score_to_add=0, possible_to_add=0):
        """
        Pass in question object, amount to increase score
        and max possible.

        Does not return anything.
        """
        category_test = Category.objects.filter(category=question.category)\
                                        .exists()

        if any([item is False for item in [category_test,
                                           score_to_add,
                                           possible_to_add,
                                           isinstance(score_to_add, int),
                                           isinstance(possible_to_add, int)]]):
            return _("error"), _("category does not exist or invalid score")

        to_find = re.escape(str(question.category)) +\
            r",(?P<score>\d+),(?P<possible>\d+),"

        match = re.search(to_find, self.score, re.IGNORECASE)

        if match:
            updated_score = int(match.group('score')) + abs(score_to_add)
            updated_possible = int(match.group('possible')) +\
                abs(possible_to_add)

            new_score = ",".join(
                [
                    str(question.category),
                    str(updated_score),
                    str(updated_possible), ""
                ])

            # swap old score for the new one
            self.score = self.score.replace(match.group(), new_score)
            self.save()

        else:
            #  if not present but existing, add with the points passed in
            self.score += ",".join(
                [
                    str(question.category),
                    str(score_to_add),
                    str(possible_to_add),
                    ""
                ])
            self.save()

    def show_exams(self):
        """
        Finds the previous quizzes marked as 'exam papers'.
        Returns a queryset of complete exams.
        """
        return Sitting.objects.filter(user=self.user, complete=True)


class SittingManager(models.Manager):

    def new_sitting(self, user, quiz):
        if quiz.random_order is True:
            question_set = quiz.question_set.all() \
                                            .select_subclasses() \
                                            .order_by('?')
        else:
            question_set = quiz.question_set.all() \
                                            .select_subclasses()

        question_set = question_set.values_list('id', flat=True)

        if len(question_set) == 0:
            raise ImproperlyConfigured('Question set of the quiz is empty. '

newnstein/quiz/forms.py
from django import forms
from django.forms.widgets import RadioSelect, Textarea
from quiz.models import Category, Quiz, Progress, Sitting, SubCategory, Question
from multichoice.models import MCQuestion, Answer
from true_false.models import TF_Question
from essay.models import Essay_Question
from django.utils.translation import ugettext_lazy as _
from django.forms import formset_factory

class QuestionForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        choice_list = [x for x in question.get_answers_list()]
        self.fields["answers"] = forms.ChoiceField(choices=choice_list,
                                                   widget=RadioSelect)


class EssayAnswerForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(EssayAnswerForm, self).__init__(*args, **kwargs)
        self.fields["answers"] = forms.CharField(
            widget=Textarea(attrs={'style': 'width:100%'}))

class QuizzesForm(forms.ModelForm):
    """
    below is from
    http://stackoverflow.com/questions/11657682/
    django-admin-interface-using-horizontal-filter-with-
    inline-manytomany-field
    """
    class Meta:
        model = Quiz
        exclude = ['class_id', 'date_added']

    questions = forms.CharField(max_length=20, widget=forms.HiddenInput(), required=False, label=_("Questions"))

    def __init__(self, *args, **kwargs):
        super(QuizzesForm, self).__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields['questions'].initial =\
                self.instance.question_set.all().select_subclasses()

    def save(self, class_id, commit=True):
        quiz = super(QuizzesForm, self).save(commit=False)
        quiz.class_id = class_id
        quiz.save()
        quiz.question_set = self.cleaned_data['questions']

        self.save_m2m()
        return quiz

class TFForm(forms.ModelForm):
    class Meta:
        model = TF_Question
        exclude = []

    def __init__(self, *args, **kwargs):
        super(TFForm, self).__init__(*args, **kwargs)
        if kwargs.get('initial'):
            if kwargs['initial'].get('quiz'):
                quiz_id = kwargs['initial']['quiz']
                self.fields['quiz'].queryset = Quiz.objects.filter(id=quiz_id)

class EssayForm(forms.ModelForm):
    class Meta:
        model = Essay_Question
        exclude = []

    def __init__(self, *args, **kwargs):
        super(EssayForm, self).__init__(*args, **kwargs)
        if kwargs.get('initial'):
            if kwargs['initial'].get('quiz'):
                quiz_id = kwargs['initial']['quiz']
                self.fields['quiz'].queryset = Quiz.objects.filter(id=quiz_id)

class MultForm(forms.ModelForm):
    class Meta:
        model = MCQuestion
        exclude = []

    def __init__(self, *args, **kwargs):
        super(MultForm, self).__init__(*args, **kwargs)
        if kwargs.get('initial'):
            if kwargs['initial'].get('quiz'):
                quiz_id = kwargs['initial']['quiz']
                self.fields['quiz'].queryset = Quiz.objects.filter(id=quiz_id)

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        exclude = ["question"]

#Creating three answers forms for the question
#In the future we would make the extra parameter dynamic
AnswerFormSet = formset_factory(AnswerForm, extra=3)

newnstein/templates/quizzes/add_question.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block head_title %}Newnstein | {{ title }}{% endblock %}

<style>
{% block style %}
.navbar-static-top {
	margin-bottom: 0px !important;
}
.jumbotron {
	color: #000;
	margin-bottom: 0px !important;
	padding-top: 12em;
}

html{
	font: 16px/24px "Arial","Helvetica",sans-serif;
}

body{
	overflow-x: hidden;
}

.navbar-default {
	border-color: transparent !important;
}

.ui-autocomplete {
	background: #FFF;
	border-radius: 0px;
	list-style: none;
}

.btn span.glyphicon {
	opacity: 0;
}
.btn.active span.glyphicon {
	opacity: 1;
}

{% endblock %}
</style>


{% block jumbotron %}

{% endblock %}




{% block content %}
<h1>{{title}} - {{quiz.title}}</h1>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-primary">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          True/False Question
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
				<form method="POST" action="true/">
					{% csrf_token %}
					<div class="form-group hidden">
						<label class="control-label" for="title">Quiz:</label>
						{{form_t.quiz|add_class:"form-control" | attr:"required:required"}}
					</div>
					<div class="form-group">
						<label class="control-label" for="title">Question:</label>
						{{form_t.content|add_class:"form-control" | attr:"required:required"}}
					</div>
					<div class="form-group">
						<div class="btn-group" data-toggle="buttons">
							<label class="btn btn-primary">
								{{form_t.correct | attr:"autocomplete:off"}}
								<span class="glyphicon glyphicon-ok"></span>
							</label>
						</div>
						Correct
					</div>
					<div class="form-group">
						<label class="control-label" for="title">Explanation:</label>
						{{form_t.explanation|add_class:"form-control"}}
					</div>
					<div class="form-group">
						<label class="control-label" for="title">Figure:</label>
						{{form_t.figure}}
					</div>
					<button class="btn btn-success btn-lg pull-right" type="submit">Add Question</button>
				</form>
      </div>
    </div>
  </div>
  <div class="panel panel-primary">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Multiple Choice Question
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
				<form method="POST" action="multiple/">
					{% csrf_token %}
					<div class="form-group hidden">
						<label class="control-label" for="title">Quiz:</label>
						{{form_q.quiz|add_class:"form-control" | attr:"required:required"}}
					</div>
					<div class="form-group">
						<label class="control-label" for="title">Question:</label>
						{{form_q.content|add_class:"form-control" | attr:"required:required"}}
					</div>
					<div class="form-group">
						<label class="control-label" for="title">Explanation:</label>
						{{form_q.explanation|add_class:"form-control"}}
					</div>
					<div class="form-group">
						<label class="control-label" for="title">Figure:</label>
						{{form_q.figure}}
					</div>
					<div id="mcanswers" class="form-group">
						<label class="control-label" for="title">Answers:</label>
						<div class="input-group mc">
				      <span class="input-group-addon">
				        <input id="correct-1" name="correct-1" type="checkbox" aria-label="...">
				      </span>
				      <input id="content-1" name="content-1" type="text" class="form-control" aria-label="...">
				    </div>
					</div>
					<a id="answer" class="btn icon-btn btn-primary active"><span class="glyphicon btn-glyphicon glyphicon-plus img-circle text-success"></span>Add</a>
					<button class="btn btn-success btn-lg pull-right" type="submit">Add Question</button>
				</form>
			</div>
    </div>
  </div>
  <div class="panel panel-primary">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Essay Question
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
				<form method="POST" action="essay/">
					{% csrf_token %}
					<div class="form-group hidden">
						<label class="control-label" for="title">Quiz:</label>
						{{form_e.quiz|add_class:"form-control" | attr:"required:required"}}
					</div>
					<div class="form-group">
						<label class="control-label" for="title">Question:</label>
						{{form_e.content|add_class:"form-control" | attr:"required:required"}}
					</div>
					<div class="form-group">
						<label class="control-label" for="title">Explanation:</label>
						{{form_e.explanation|add_class:"form-control"}}
					</div>
					<div class="form-group">
						<label class="control-label" for="title">Figure:</label>
						{{form_e.figure}}
					</div>
					<button class="btn btn-success btn-lg pull-right" type="submit">Add Question</button>
				</form>
			</div>
    </div>
  </div>
</div>
<a class="btn btn-primary btn-lg pull-right" href="../view" role="button">Review Quiz</a>
<script>
	$(document).ready(function() {
		$("#answer").click(function(){
				var n = $( ".mc" ).length + 1;
				$("#mcanswers").append('<div class="input-group mc"><span class="input-group-addon"><input id="correct-' + n + '" name="correct-' + n + '" type="checkbox" aria-label="..."></span><input id="content-' + n + '" name="content-' + n + '" type="text" class="form-control" aria-label="...">	</div>');
		});

		$('select option[value="{{quiz_id}}"]').attr("selected",true);
	});
</script>

	{% endblock %}

newnstein/templates/quizzes/add_quiz.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block head_title %}Newnstein | {{ title }}{% endblock %}

<style>
{% block style %}
.navbar-static-top {
	margin-bottom: 0px !important;
}
.jumbotron {
	color: #000;
	margin-bottom: 0px !important;
	padding-top: 12em;
}

html{
	font: 16px/24px "Arial","Helvetica",sans-serif;
}

body{
	overflow-x: hidden;
}

.navbar-default {
    border-color: transparent !important;
}

.ui-autocomplete {
    background: #FFF;
    border-radius: 0px;
		list-style: none;
}

.btn span.glyphicon {
	opacity: 0;
}
.btn.active span.glyphicon {
	opacity: 1;
}

{% endblock %}
</style>


{% block jumbotron %}

{% endblock %}




{% block content %}
<div class="row">
	<div class="stepwizard mt-2x">
	    <div class="stepwizard-row setup-panel">
	        <div class="stepwizard-step">
	            <a href="#step-1" type="button" class="btn btn-primary btn-circle">1</a>
	            <p>Quiz Information</p>
	        </div>
	        <div class="stepwizard-step">
	            <a href="#step-2" type="button" class="btn btn-default btn-circle" disabled="disabled">2</a>
	            <p>Quiz Grading</p>
	        </div>
	        <div class="stepwizard-step">
	            <a href="#step-3" type="button" class="btn btn-default btn-circle" disabled="disabled">3</a>
	            <p>Additional Options</p>
	        </div>
	    </div>
	</div>
	<form role="form" method="POST">
		{% csrf_token %}
	    <div class="row setup-content" id="step-1">
	        <div class="col-xs-12">
	            <div class="col-md-12">
	                <h3> Quiz Information</h3>
									<div class="form-group">
								    <label class="control-label" for="title">Quiz Name:</label>
										{{form.title|add_class:"form-control" | attr:"required:required"}}
								  </div>
									<div class="form-group">
								    <label class="control-label" for="category">Category:</label>
										{{form.category|add_class:"form-control"}}
								  </div>
									<div class="form-group">
								    <label class="control-label" for="description">Description:</label>
										{{form.description|add_class:"form-control"}}
								  </div>
	                <button class="btn btn-primary nextBtn btn-lg pull-right" type="button" >Next</button>
	            </div>
	        </div>
	    </div>
			<script>
			$(function() {
				var availableTags = [
					{% for lecture in class_lectures %}
						"{{lecture.title}}",
					{% endfor %}
				];
				function split( val ) {
					return val.split( /,\s*/ );
				}
				function extractLast( term ) {
					return split( term ).pop();
				}

				$( "#id_category" )
					// don't navigate away from the field on tab when selecting an item
					.bind( "keydown", function( event ) {
						if ( event.keyCode === $.ui.keyCode.TAB &&
								$( this ).autocomplete( "instance" ).menu.active ) {
							event.preventDefault();
						}
					})
					.autocomplete({
						minLength: 0,
						source: function( request, response ) {
							// delegate back to autocomplete, but extract the last term
							response( $.ui.autocomplete.filter(
								availableTags, extractLast( request.term ) ) );
						},
						focus: function() {
							// prevent value inserted on focus
							return false;
						},
						select: function( event, ui ) {
							var terms = split( this.value );
							// remove the current input
							terms.pop();
							// add the selected item
							terms.push( ui.item.value );
							// add placeholder to get the comma-and-space at the end
							terms.push( "" );
							this.value = terms.join( ", " );
							return false;
						}
					});
			});
			</script>
	    <div class="row setup-content" id="step-2">
	        <div class="col-xs-12">
	            <div class="col-md-12">
	                <h3> Quiz Grading</h3>
									<div class="form-group">
								    <label class="control-label" for="pass_mark">Pass mark:</label>
										{{form.pass_mark|add_class:"form-control" | attr:"required:required"}}
								  </div>
									<div class="form-group">
								    <label class="control-label" for="success_text">Success Text:</label>
										{{form.success_text|add_class:"form-control"}}
								  </div>
									<div class="form-group">
								    <label class="control-label" for="fail_text">Fail Text:</label>
										{{form.fail_text|add_class:"form-control"}}
								  </div>
	                <button class="btn btn-primary nextBtn btn-lg pull-right" type="button" >Next</button>
	            </div>
	        </div>
	    </div>
	    <div class="row setup-content" id="step-3">
	        <div class="col-xs-12">
	            <div class="col-md-12">
	                <h3> Additional Options</h3>
									<div class="form-group">
										<div class="btn-group" data-toggle="buttons">
											<label class="btn btn-primary">
												{{form.random_order | attr:"autocomplete:off"}}
												<span class="glyphicon glyphicon-ok"></span>
											</label>
										</div>
										Random Order
								  </div>
									<div class="form-group">
										<div class="btn-group" data-toggle="buttons">
											<label class="btn btn-primary">
												{{form.answers_at_end | attr:"autocomplete:off"}}
												<span class="glyphicon glyphicon-ok"></span>
											</label>
										</div>
										Answers at end
								  </div>
									<div class="form-group">
										<div class="btn-group" data-toggle="buttons">
											<label class="btn btn-primary">
												{{form.exam_paper | attr:"autocomplete:off"}}
												<span class="glyphicon glyphicon-ok"></span>
											</label>
										</div>
										Exam Paper
								  </div>
									<div class="form-group">
										<div class="btn-group" data-toggle="buttons">
											<label class="btn btn-primary">
												{{form.single_attempt | attr:"autocomplete:off"}}
												<span class="glyphicon glyphicon-ok"></span>
											</label>
										</div>
										Single Attempt
								  </div>
	                <button class="btn btn-success btn-lg pull-right" type="submit">Finish!</button>
	            </div>
	        </div>
	    </div>
	</form>
</div>

	<!-- <h2>{{ title }}</h2>
	<div class="row">
		{% if response %}
			{{response | safe}}
		{% endif %}

    <form method="POST" action="">{% csrf_token %}
			{% if mult %}
				{{ form_q | crispy}}
				<hr/>
				<h3> Answers </h3>
				{{ form_a | crispy}}
			{%else%}
			{{ form | crispy}}
			{% endif %}
			<script type="text/javascript">
			 $(function() {
					 var availableTags = [
						 {%for category in categories%}
							 "{{ category }}",
						 {% endfor %}
					 ];
					 $( "#id_category" ).autocomplete({
						 source: availableTags
					 });
			 });
			</script>
      <input type="submit" class="btn btn-primary" value="Add Questions">
    </form>
</div> -->
<script src="{% static 'js/form-wizard.js' %}"></script>
{% endblock %}

newnstein/templates/quizzes/quiz_list.html
{% extends "dashboard/base.html" %}

{% block title %}{{title}}{% endblock %}

{% block content %}
  <h1>{{title}}</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Category</th>
        {% if user_type == "TE" %}
        <th>Order</th>
        {% endif %}
        <th>Exam</th>
        <th>Attempts</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    {% for quiz in quizzes %}
      <tr>
        <td>{{quiz.title}}</td>

        {% if quiz.category %}
          <td>{{quiz.category}}</td>
        {% else %}
          <td>N/A</td>
        {% endif %}

        {% if user_type == "TE" %}
          {% if quiz.random_order == 1 %}
            <td>Random</td>
          {% else %}
            <td>By Question</td>
          {% endif %}
        {% endif %}

        {% if quiz.exam_paper == 1 %}
          <td>True</td>
        {% else %}
          <td>False</td>
        {% endif %}
        {% if quiz.single_attempt == 1 %}
          <td>Single</td>
        {% else %}
          <td>Multiple</td>
        {% endif %}
        <td>
          {% if user_type == "TE" %}
            <a class="btn btn-primary" href="{{quiz.id}}/view" role="button">View Quiz</a>
          {% else %}
            <a class="btn btn-primary" href="{{quiz.id}}/take" role="button">View Quiz</a>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}