newnstein/newnstein/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls import (
handler400, handler403, handler404, handler500
)

handler400 = 'home.views.error400'
handler403 = 'home.views.error403'
handler404 = 'home.views.error404'
handler500 = 'home.views.error500'

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'home.views.home', name='home'),
    url(r'^(?P<class_id>\d+)/', include('dashboard.urls')),
    url(r'^dashboard/$', 'dashboard.views.dashboard', name="dashboard"),
    url(r'^accounts/', include('account.urls')),
    url(r'^settings/', include('settings.urls')),
]

newnstein/quiz/urls.py
from django.conf.urls import patterns, url

from .views import CategoriesListView,\
    ViewQuizListByCategory, QuizUserProgressView, QuizMarkingList,\
    QuizMarkingDetail, QuizDetailView, QuizTake


urlpatterns = patterns('',
                        url(r'^$', 'quiz.views.view_all_quizzes', name='view_all_quizzes'),
                        url(r'^add/$', 'quiz.views.create_quiz', name='create_quiz'),
                        url(r'^(?P<quiz_id>\d+)/edit/(?P<question_id>\d+)/$', 'quiz.views.edit_quiz', name='edit_quiz'),
                        url(r'^(?P<quiz_id>\d+)/edit/(?P<question_id>\d+)/true/$', 'quiz.views.update_tf_question', name='update_tf_question'),
                        url(r'^(?P<quiz_id>\d+)/edit/(?P<question_id>\d+)/multiple/$', 'quiz.views.update_mc_question', name='update_mc_question'),
                        url(r'^(?P<quiz_id>\d+)/edit/(?P<question_id>\d+)/essay/$', 'quiz.views.update_essay_question', name='update_essay_question'),
                        url(r'^(?P<quiz_id>\d+)/view/$', 'quiz.views.view_quiz', name='view_quiz'),
                        url(r'^(?P<quiz_id>\d+)/delete/$', 'quiz.views.delete_quiz', name='delete_quiz'),
                        url(r'^(?P<quiz_id>\d+)/add_question/$', 'quiz.views.add_question', name='add_question'),
                        url(r'^(?P<quiz_id>\d+)/add_question/true/$', 'quiz.views.add_tf_question', name='add_tf_question'),
                        url(r'^(?P<quiz_id>\d+)/add_question/multiple/$', 'quiz.views.add_mc_question', name='add_mc_question'),
                        url(r'^(?P<quiz_id>\d+)/add_question/essay/$', 'quiz.views.add_essay_question', name='add_essay_question'),

                        url(regex=r'^category/$', view=CategoriesListView.as_view(), name='quiz_category_list_all'),
                        url(regex=r'^category/(?P<category_name>[\w|\W-]+)/$', view=ViewQuizListByCategory.as_view(), name='quiz_category_list_matching'),
                        url(regex=r'^progress/$', view=QuizUserProgressView.as_view(), name='quiz_progress'),
                        url(regex=r'^marking/$', view=QuizMarkingList.as_view(), name='quiz_marking'),
                        url(regex=r'^marking/(?P<pk>[\d.]+)/$', view=QuizMarkingDetail.as_view(), name='quiz_marking_detail'),
                        url(regex=r'^(?P<slug>\d+)/$', view=QuizDetailView.as_view(), name='quiz_start_page'),
                        url(regex=r'^(?P<quiz_name>[\w-]+)/take/$', view=QuizTake.as_view(), name='quiz_question'),
)

newnstein/quiz/models.py
from __future__ import unicode_literals
import re
import json
import datetime

from django.db import models
from django.core.exceptions import ValidationError, ImproperlyConfigured
from django.core.validators import MaxValueValidator
from django.utils.translation import ugettext as _
from django.utils.timezone import now
from django.utils.encoding import python_2_unicode_compatible
from django.conf import settings

from model_utils.managers import InheritanceManager


class CategoryManager(models.Manager):

    def new_category(self, category):
        new_category = self.create(category=re.sub('\s+', '-', category)
                                   .lower())

        new_category.save()
        return new_category


@python_2_unicode_compatible
class Category(models.Model):

    category = models.CharField(
        verbose_name=_("Category"),
        max_length=250, blank=True,
        unique=True, null=True)

    objects = CategoryManager()

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.category


@python_2_unicode_compatible
class SubCategory(models.Model):

    sub_category = models.CharField(
        verbose_name=_("Sub-Category"),
        max_length=250, blank=True, null=True)

    category = models.ForeignKey(
        Category, null=True, blank=True,
        verbose_name=_("Category"))

    objects = CategoryManager()

    class Meta:
        verbose_name = _("Sub-Category")
        verbose_name_plural = _("Sub-Categories")

    def __str__(self):
        return self.sub_category + " (" + self.category.category + ")"


@python_2_unicode_compatible
class Quiz(models.Model):

    title = models.CharField(
        verbose_name=_("Title"),
        max_length=60, blank=False)

    description = models.TextField(
        verbose_name=_("Description"),
        blank=True, help_text=_("a description of the quiz"))

    category = models.CharField(
        max_length=60,
        blank=True, verbose_name=_("Category"))

    random_order = models.BooleanField(
        blank=False, default=False,
        verbose_name=_("Random Order"),
        help_text=_("Display the questions in "
                    "a random order or as they "
                    "are set?"))

    max_questions = models.PositiveIntegerField(
        blank=True, null=True, verbose_name=_("Max Questions"),
        help_text=_("Number of questions to be answered on each attempt."))

    answers_at_end = models.BooleanField(
        blank=False, default=False,
        help_text=_("Correct answer is NOT shown after question."
                    " Answers displayed at the end."),
        verbose_name=_("Answers at end"))

    exam_paper = models.BooleanField(
        blank=False, default=False,
        help_text=_("If yes, the result of each"
                    " attempt by a user will be"
                    " stored. Necessary for marking."),
        verbose_name=_("Exam Paper"))

    single_attempt = models.BooleanField(
        blank=False, default=False,
        help_text=_("If yes, only one attempt by"
                    " a user will be permitted."
                    " Non users cannot sit this exam."),
        verbose_name=_("Single Attempt"))

    pass_mark = models.SmallIntegerField(
        blank=True, default=0,
        verbose_name=_("Pass Mark"),
        help_text=_("Percentage required to pass exam."),
        validators=[MaxValueValidator(100)])

    success_text = models.TextField(
        blank=True, help_text=_("Displayed if user passes."),
        verbose_name=_("Success Text"))

    fail_text = models.TextField(
        verbose_name=_("Fail Text"),
        blank=True, help_text=_("Displayed if user fails."))

    draft = models.BooleanField(
        blank=True, default=False,
        verbose_name=_("Draft"),
        help_text=_("If yes, the quiz is not displayed"
                    " in the quiz list and can only be"
                    " taken by users who can edit"
                    " quizzes."))

    date_added = models.DateTimeField(
        default=datetime.datetime.now,
        verbose_name=_("Date"),
        blank=True)

    class_id = models.IntegerField(default=1)


    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        if self.single_attempt is True:
            self.exam_paper = True

        if self.pass_mark > 100:
            raise ValidationError('%s is above 100' % self.pass_mark)

        super(Quiz, self).save(force_insert, force_update, *args, **kwargs)

    class Meta:
        verbose_name = _("Quiz")
        verbose_name_plural = _("Quizzes")

    def __str__(self):
        return self.title

    def get_questions(self):
        return self.question_set.all().select_subclasses()

    @property
    def get_max_score(self):
        return self.get_questions().count()

    def anon_score_id(self):
        return str(self.id) + "_score"

    def anon_q_list(self):
        return str(self.id) + "_q_list"

    def anon_q_data(self):
        return str(self.id) + "_data"


class ProgressManager(models.Manager):

    def new_progress(self, user):
        new_progress = self.create(user=user,
                                   score="")
        new_progress.save()
        return new_progress


class Progress(models.Model):
    """
    Progress is used to track an individual signed in users score on different
    quiz's and categories

    Data stored in csv using the format:
        category, score, possible, category, score, possible, ...
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL, verbose_name=_("User"))

    score = models.CommaSeparatedIntegerField(max_length=1024,
                                              verbose_name=_("Score"))

    objects = ProgressManager()

    class Meta:
        verbose_name = _("User Progress")
        verbose_name_plural = _("User progress records")

    @property
    def list_all_cat_scores(self):
        """
        Returns a dict in which the key is the category name and the item is
        a list of three integers.

        The first is the number of questions correct,
        the second is the possible best score,
        the third is the percentage correct.

        The dict will have one key for every category that you have defined
        """
        score_before = self.score
        output = {}

        for cat in Category.objects.all():
            to_find = re.escape(cat.category) + r",(\d+),(\d+),"
            #  group 1 is score, group 2 is highest possible

            match = re.search(to_find, self.score, re.IGNORECASE)

            if match:
                score = int(match.group(1))
                possible = int(match.group(2))

                try:
                    percent = int(round((float(score) / float(possible))
                                        * 100))
                except:
                    percent = 0

                output[cat.category] = [score, possible, percent]

            else:  # if category has not been added yet, add it.
                self.score += cat.category + ",0,0,"
                output[cat.category] = [0, 0]

        if len(self.score) > len(score_before):
            # If a new category has been added, save changes.
            self.save()

        return output

    def update_score(self, question, score_to_add=0, possible_to_add=0):
        """
        Pass in question object, amount to increase score
        and max possible.

        Does not return anything.
        """
        category_test = Category.objects.filter(category=question.category)\
                                        .exists()

        if any([item is False for item in [category_test,
                                           score_to_add,
                                           possible_to_add,
                                           isinstance(score_to_add, int),
                                           isinstance(possible_to_add, int)]]):
            return _("error"), _("category does not exist or invalid score")

        to_find = re.escape(str(question.category)) +\
            r",(?P<score>\d+),(?P<possible>\d+),"

        match = re.search(to_find, self.score, re.IGNORECASE)

        if match:
            updated_score = int(match.group('score')) + abs(score_to_add)
            updated_possible = int(match.group('possible')) +\
                abs(possible_to_add)

            new_score = ",".join(
                [
                    str(question.category),
                    str(updated_score),
                    str(updated_possible), ""
                ])

            # swap old score for the new one
            self.score = self.score.replace(match.group(), new_score)
            self.save()

        else:
            #  if not present but existing, add with the points passed in
            self.score += ",".join(
                [
                    str(question.category),
                    str(score_to_add),
                    str(possible_to_add),
                    ""
                ])
            self.save()

    def show_exams(self):
        """
        Finds the previous quizzes marked as 'exam papers'.
        Returns a queryset of complete exams.
        """
        return Sitting.objects.filter(user=self.user, complete=True)


class SittingManager(models.Manager):

    def new_sitting(self, user, quiz):
        if quiz.random_order is True:
            question_set = quiz.question_set.all() \
                                            .select_subclasses() \
                                            .order_by('?')
        else:
            question_set = quiz.question_set.all() \
                                            .select_subclasses()

        question_set = question_set.values_list('id', flat=True)

        if len(question_set) == 0:
            raise ImproperlyConfigured('Question set of the quiz is empty. '

newnstein/templates/stats/exercise_stats.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}


{% block head_title %}Newnstein | {{ title }}{% endblock %}

<style>
{% block style %}
.navbar-static-top {
  margin-bottom: 0px !important;
}
.jumbotron {
  color: #000;
  margin-bottom: 0px !important;
  padding-top: 12em;
}

html{
  font: 16px/24px "Arial","Helvetica",sans-serif;
}

body{
  overflow-x: hidden;
}

html, body {
  width:  100%;
  height: 100%;
  margin: 0px;
}

.navbar-default {
  border-color: transparent !important;
}

{% endblock %}
</style>



{% block jumbotron %}

{% endblock %}




{% block content %}
<script>
$(document).ready(
  function() {
    //this variable will keep track of the chart
    var clientsChart;
    $("select#exercise_selector").change(function() {
      var determineexercise = $(this).val();
      var html = "";
      //this funtion will populate the table
      {% for exercise in exercise_time%}
      if(determineexercise == {{exercise.exercise_id.id}}) {
        html += "<tr><td>{{exercise.user_id.get_full_name}}</td><td>{{exercise.duration | date:'H:i:s'}} / {{exercise.visits}}</td></tr>";
      }
      {% endfor %}

      //this function will populate the graph
      var description = new Array();
      var myvalues = new Array();
      {% for exercise in exercise_time%}
      if(determineexercise == {{exercise.exercise_id.id}}) {
        description.push("{{exercise.user_id.get_full_name}}");
        myvalues.push("{{exercise.duration|date:'His'}}");
      }
      {% endfor %}
      var barData = {
        labels: description,
        datasets: [
          {
            fillColor: '#cdeffe',
            strokeColor: '#68cefd',
            highlightFill: '#68cefd',
            highlightStroke:'#03A9F4',
            data: myvalues
          },
        ]
      };

      //clear the values before writing. Might need to change to update instead of deleting/adding
      $('#exercise_table > tbody').empty();
      $('#empty_table').empty();
      if(clientsChart){
        clientsChart.destroy();
      }

      //no data was found. display appropriate data
      if (html=="") {
        $('#empty_table').append("There is no available data for this class");
      }
      //data was found, populate the table and graph
      else {
        $('#exercise_table > tbody').append(html);
        var context = document.getElementById('chart-stats').getContext('2d');
        var table_context = document.getElementById('statistics-table');
        context.canvas.width  = window.innerWidth/2;
        context.canvas.height = window.innerHeight/2;
        clientsChart = new Chart(context).Bar(barData, {
          scaleShowLabels: false,
          animation: true,
          responsive: true,
          barStrokeWidth : 10,
        });
      }
    })
  });
  </script>

  <h2>{{title}}</h2>
  <div class="panel panel-default">
    <div class="panel-heading">
      <i class="fa fa-bar-chart-o fa-fw"></i> Exercise Time Statistics
      <div class="pull-right">
        <div class="btn-group">
          <label id="initial_select" name="initial_select"> Select one of the exercises</label>
          <select class="form-control" name="exercise_selector" id="exercise_selector">
            <option selected="selected" disabled>Select a exercise</option>
            {% for exercise in exercise_list %}
              {% for available_exercise in available_exercises %}
                {% if exercise.exercise_id == available_exercise.id%}
                  <option value="{{exercise.id}}">{{available_exercise.title}}</option>
                {% endif %}
              {% endfor %}
            {% endfor %}
          </select>
        </div>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-4">
            <div class="table-responsive" id="statistics-table">
              <table class="table table-bordered table-hover table-striped" id="exercise_table" name="exercise_table">
                <thead>
                  <tr>
                    <th>Student</th>
                    <th>Time / Visits</th>
                  </tr>
                </thead>
                <tbody id="table_body" name="table_body">
                </tbody>
              </table>
              <label id="empty_table" name="empty_table"></label>
            </div>
          </div>
          <div class="col-lg-8">
            <canvas id="chart-stats"></canvas>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}

newnstein/templates/stats/lecture_stats.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}


{% block head_title %}Newnstein | {{ title }}{% endblock %}

<style>
{% block style %}
.navbar-static-top {
  margin-bottom: 0px !important;
}
.jumbotron {
  color: #000;
  margin-bottom: 0px !important;
  padding-top: 12em;
}

html{
  font: 16px/24px "Arial","Helvetica",sans-serif;
}

body{
  overflow-x: hidden;
}

html, body {
  width:  100%;
  height: 100%;
  margin: 0px;
}

.navbar-default {
  border-color: transparent !important;
}

{% endblock %}
</style>



{% block jumbotron %}

{% endblock %}




{% block content %}
<script>
$(document).ready(
  function() {
    //this variable will keep track of the chart
    var clientsChart;
    $("select#lecture_selector").change(function() {
      var determineLecture = $(this).val();
      var html = "";
      //this funtion will populate the table
      {% for lecture in lecture_time%}
        if(determineLecture == {{lecture.lecture_id.id}}) {
          html += "<tr><td>{{lecture.user_id.get_full_name}}</td><td>{{lecture.lecture_id.title}}</td><td>{{lecture.duration | date:'H:i:s'}} / {{lecture.visits}}</td></tr>";
        }
      {% endfor %}

      //this function will populate the graph
      var description = new Array();
      var myvalues = new Array();
      {% for lecture in lecture_time%}
        if(determineLecture == {{lecture.lecture_id.id}}) {
          description.push("{{lecture.user_id.get_full_name}}");
          myvalues.push("{{lecture.duration|date:'His'}}");
        }
      {% endfor %}
      var barData = {
        labels: description,
        datasets: [
          {
            fillColor: '#cdeffe',
            strokeColor: '#68cefd',
            highlightFill: '#68cefd',
            highlightStroke:'#03A9F4',
            data: myvalues
          },
        ]
      };

      //clear the values before writing. Might need to change to update instead of deleting/adding
      $('#lecture_table > tbody').empty();
      $('#empty_table').empty();
      if(clientsChart){
        clientsChart.destroy();
      }

      //no data was found. display appropriate data
      if (html=="") {
        $('#empty_table').append("There is no available data for this class");
      }
      //data was found, populate the table and graph
      else {
        $('#lecture_table > tbody').append(html);
        var context = document.getElementById('chart-stats').getContext('2d');
        var table_context = document.getElementById('statistics-table');
        context.canvas.width  = window.innerWidth/2;
        context.canvas.height = window.innerHeight/2;
        clientsChart = new Chart(context).Bar(barData, {
          scaleShowLabels: false,
          animation: true,
          responsive: true,
          barStrokeWidth : 10,
        });
      }
    })
});
</script>

<h2>{{title}}</h2>
<div class="panel panel-default">
  <div class="panel-heading">
    <i class="fa fa-bar-chart-o fa-fw"></i> Lecture Time Statistics
    <div class="pull-right">
      <div class="btn-group">
        <label id="initial_select" name="initial_select"> Select one of the lectures</label>
        <select class="form-control" name="lecture_selector" id="lecture_selector">
          <option selected="selected" disabled>Select a lecture</option>
          {% for lecture in nav_list %}
          <option value="{{lecture.id}}">{{lecture.title}}</option>
          {% endfor %}
        </select>
      </div>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <div class="row">
        <div class="col-lg-4">
          <div class="table-responsive" id="statistics-table">
            <table class="table table-bordered table-hover table-striped" id="lecture_table" name="lecture_table">
              <thead>
                <tr>
                  <th>Student</th>
                  <th>Lecture</th>
                  <th>Time / Visits</th>
                </tr>
              </thead>
              <tbody id="table_body" name="table_body">
              </tbody>
            </table>
            <label id="empty_table" name="empty_table"></label>
          </div>
        </div>
        <div class="col-lg-8">
          <canvas id="chart-stats"></canvas>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

newnstein/templates/stats/quiz_stats.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}


{% block head_title %}Newnstein | {{ title }}{% endblock %}

<style>
{% block style %}
.navbar-static-top {
  margin-bottom: 0px !important;
}
.jumbotron {
  color: #000;
  margin-bottom: 0px !important;
  padding-top: 12em;
}

html{
  font: 16px/24px "Arial","Helvetica",sans-serif;
}

body{
  overflow-x: hidden;
}

html, body {
  width:  100%;
  height: 100%;
  margin: 0px;
}

.navbar-default {
  border-color: transparent !important;
}

{% endblock %}
</style>



{% block jumbotron %}

{% endblock %}




{% block content %}
<script>
$(document).ready(
  function() {
    //this variable will keep track of the chart
    var clientsChart;
    $("select#quiz_selector").change(function() {
      var determinequiz = $(this).val();
      var html = "";
      //this funtion will populate the table
      {% for quiz in quiz_time%}
      if(determinequiz == {{quiz.quiz_id.id}}) {
        html += "<tr><td>{{quiz.user_id.get_full_name}}</td><td>{{quiz.quiz_id.title}}</td><td>{{quiz.duration | date:'H:i:s'}} / {{quiz.visits}}</td></tr>";
      }
      {% endfor %}

      //this function will populate the graph
      var description = new Array();
      var myvalues = new Array();
      {% for quiz in quiz_time%}
      if(determinequiz == {{quiz.quiz_id.id}}) {
        description.push("{{quiz.user_id.get_full_name}}");
        myvalues.push("{{quiz.duration|date:'His'}}");
      }
      {% endfor %}
      var barData = {
        labels: description,
        datasets: [
          {
            fillColor: '#cdeffe',
            strokeColor: '#68cefd',
            highlightFill: '#68cefd',
            highlightStroke:'#03A9F4',
            data: myvalues
          },
        ]
      };

      //clear the values before writing. Might need to change to update instead of deleting/adding
      $('#quiz_table > tbody').empty();
      $('#empty_table').empty();
      if(clientsChart){
        clientsChart.destroy();
      }

      //no data was found. display appropriate data
      if (html=="") {
        $('#empty_table').append("There is no available data for this class");
      }
      //data was found, populate the table and graph
      else {
        $('#quiz_table > tbody').append(html);
        var context = document.getElementById('chart-stats').getContext('2d');
        var table_context = document.getElementById('statistics-table');
        context.canvas.width  = window.innerWidth/2;
        context.canvas.height = window.innerHeight/2;
        clientsChart = new Chart(context).Bar(barData, {
          scaleShowLabels: false,
          animation: true,
          responsive: true,
          barStrokeWidth : 10,
        });
      }
    })
  });
  </script>

  <h2>{{title}}</h2>
  <div class="panel panel-default">
    <div class="panel-heading">
      <i class="fa fa-bar-chart-o fa-fw"></i> Quiz Time Statistics
      <div class="pull-right">
        <div class="btn-group">
          <label id="initial_select" name="initial_select"> Select one of the quizs</label>
          <select class="form-control" name="quiz_selector" id="quiz_selector">
            <option selected="selected" disabled>Select a quiz</option>
            {% for quiz in quiz_list %}
            <option value="{{quiz.id}}">{{quiz.title}}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-4">
            <div class="table-responsive" id="statistics-table">
              <table class="table table-bordered table-hover table-striped" id="quiz_table" name="quiz_table">
                <thead>
                  <tr>
                    <th>Student</th>
                    <th>Quiz</th>
                    <th>Time / Visits</th>
                  </tr>
                </thead>
                <tbody id="table_body" name="table_body">
                </tbody>
              </table>
              <label id="empty_table" name="empty_table"></label>
            </div>
          </div>
          <div class="col-lg-8">
            <canvas id="chart-stats"></canvas>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}